package com.amalitech.dydamodbtodoapp.dynamodb_todo_app.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;

import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@DynamoDBTable(tableName = "todo")
public class Todo {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String title;
    @DynamoDBAttribute
    private String description;
    @DynamoDBAttribute
    private boolean completed;
    @DynamoDBAttribute
    private String createdAt;
    @DynamoDBAttribute
    private String updatedAt;

    public Todo() {
        this.createdAt = LocalDateTime.now().toString();
        this.updatedAt = LocalDateTime.now().toString();
    }
}
